'use strict';

const { cast, makeSmartQuote, applyFont } = require('../cast');

const config = require('../config');
const mumaker = require('mumaker');
const fetch = require('node-fetch');

// ── TEXT EFFECTS — ephoto360 effects ──────────────────
// All 18 effects ported to NEXUS-MD format using mumaker

// Map of command name -> ephoto360 URL
const EFFECTS = {
  '1917':       'https://en.ephoto360.com/1917-style-text-effect-523.html',
  'arena':      'https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html',
  'blackpink':  'https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html',
  'devil':      'https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html',
  'fire':       'https://en.ephoto360.com/flame-lettering-effect-372.html',
  'glitch':     'https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html',
  'hacker':     'https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html',
  'ice':        'https://en.ephoto360.com/ice-text-effect-online-101.html',
  'impressive': 'https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html',
  'leaves':     'https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html',
  'light':      'https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html',
  'matrix':     'https://en.ephoto360.com/matrix-text-effect-154.html',
  'metallic':   'https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html',
  'neon':       'https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html',
  'purple':     'https://en.ephoto360.com/purple-text-effect-online-100.html',
  'sand':       'https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html',
  'snow':       'https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html',
  'thunder':    'https://en.ephoto360.com/thunder-text-effect-online-97.html',
};

// Register a cast() for each effect
for (const [name, url] of Object.entries(EFFECTS)) {
  cast({
    pattern: name,
    desc: `Generate a ${name} style text effect image.`,
    category: 'textfx',
    react: '🎨',
    filename: __filename
  }, async (conn, mek, m, { q, reply }) => {
    const text = q && q.trim();
    if (!text) return reply(`✏️ Please provide the text you want styled.\nExample: *${config.PREFIX || ':'}${name} YourName*`);

    await reply('⏳ Generating your image, please wait...');

    try {
      const result = await mumaker.ephoto(url, text);
      if (!result || !result.image) throw new Error('No image returned from the API.');

      await conn.sendMessage(m.chat, {
        image: { url: result.image },
        caption: `✨ *${name.toUpperCase()} Effect*\n_Generated by ${config.BOT_NAME || 'NEXUS-MD'}_`
      }, { quoted: mek });

    } catch (e) {
      console.error(`[texteffects:${name}]`, e.message);
      await reply(`❌ Failed to generate the *${name}* effect. The site may be temporarily unavailable, try again in a moment.`);
    }
  });
}

// ── TEXT PRO — mumaker text effects ───────────────────

async function textpro(url, texts) {
  try {
    const { textpro: tp } = require('mumaker');
    return await tp(url, texts);
  } catch { return null; }
}

const tpCmd = (pattern, desc, urlPath, dual = false) => {
  cast({ pattern, desc, category: 'textfx', filename: __filename },
  async (conn, mek, m, { from, q, reply }) => {
    try {
      const prefix = config.PREFIX || '/';
      let text1, text2;
      if (dual) {
        [text1, text2] = (q || '').split(';').map(s => s.trim());
        if (!text1 || !text2) return reply(`*Example:* ${prefix}${pattern} Text1;Text2`);
      } else {
        text1 = q;
        if (!text1) return reply(`*Example:* ${prefix}${pattern} YourName`);
      }
      const url = urlPath.startsWith('http') ? urlPath : `https://textpro.me/${urlPath}.html`;
      await conn.sendMessage(from, { text: '⏳ *Generating...*' }, { quoted: mek });
      const r = await textpro(url, dual ? [text1, text2] : [text1]);
      if (r?.image) {
        await conn.sendMessage(from, { image: { url: r.image }, caption: `_${config.BOT_NAME || 'NEXUS-MD'}_` }, { quoted: mek });
      } else {
        reply('*_Failed to generate. Try again!_*');
      }
    } catch (e) { reply(`❌ Error: ${e.message}`); }
  });
};

tpCmd('glow',       'Glowing text effect',          'https://ephoto360.com/hieu-ung-chu/tao-hieu-ung-chu-mam-anh-sang-74.html');
tpCmd('glitch',     'Digital glitch text',           'https://ephoto360.com/tao-hieu-ung-chu-digital-glitch-truc-tuyen-941.html');
tpCmd('pixel',      'Pixel glitch text',             'https://ephoto360.com/tao-hieu-ung-chu-pixel-glitch-truc-tuyen-940.html');
tpCmd('grafiti',    'Graffiti text style',           'https://ephoto360.com/tao-hieu-ung-chu-graffiti-duong-pho-an-tuong-online-795.html');
tpCmd('grafiti2',   'Graffiti text style 2',         'https://ephoto360.com/hieu-ung-chu/chu-graffiti-online-mau-8-182.html');
tpCmd('grafiti3',   'Graffiti text (dual)',          'tao-hieu-ung-chu-graffiti-sieu-ngau-online-794', true);
tpCmd('grafiti4',   'Cover graffiti (dual)',         'https://ephoto360.com/hieu-ung-chu/tao-cover-graffiti-online-181.html', true);
tpCmd('gradient',   'Gradient 3D text (dual)',       'https://ephoto360.com/tao-logo-gradient-3d-truc-tuyen-501.html', true);
tpCmd('wtone',      'Watercolor tone (dual)',        'https://ephoto360.com/tao-logo-chu-truc-tuyen-499.html', true);
tpCmd('phub',       'PornHub style logo (dual)',     'https://ephoto360.com/tao-logo-phong-cach-pornhub-612.html', true);
tpCmd('avenger',    'Avengers logo (dual)',          'https://ephoto360.com/tao-logo-3d-phong-cach-avengers-445.html', true);
tpCmd('marvel',     'Marvel logo (dual)',            'https://ephoto360.com/tao-logo-phong-cach-marvel-419.html', true);
tpCmd('sea',        'Deep sea metal text',           'create-3d-deep-sea-metal-text-effect-online-1053');
tpCmd('horror',     'Horror blood text',             'horror-blood-text-effect-online-883');
tpCmd('joker',      'Joker logo text',               'create-logo-joker-online-934');
tpCmd('metallic',   'Metallic text',                 'create-a-metallic-text-effect-free-online-1041');
tpCmd('luxury',     '3D luxury gold text',           '3d-luxury-gold-text-effect-online-1003');
tpCmd('glue',       '3D glue text',                  'create-3d-glue-text-effect-with-realistic-style-986');
tpCmd('fabric',     'Fabric text',                   'fabric-text-effect-online-964');
tpCmd('toxic',      'Toxic text',                    'toxic-text-effect-online-901');
tpCmd('ancient',    '3D golden ancient text',        '3d-golden-ancient-text-effect-online-free-1060');
tpCmd('cloud',      'Cloud sky text',                'create-a-cloud-text-effect-on-the-sky-online-1004');
tpCmd('transformer','Transformer text',              'create-a-transformer-text-effect-online-1035');
tpCmd('thunder',    'Thunder text',                  'online-thunder-text-effect-generator-1031');
tpCmd('scifi',      'Sci-fi 3D text',                'create-3d-sci-fi-text-effect-online-1050');
tpCmd('sand',       'Sand beach text',               'write-in-sand-summer-beach-free-online-991');
tpCmd('rainbow',    '3D rainbow text',               '3d-rainbow-color-calligraphy-text-effect-1049');
tpCmd('pencil',     'Sketch/pencil text',            'create-a-sketch-text-effect-online-1044');
tpCmd('neon',       '3D neon text',                  'create-3d-neon-light-text-effect-online-1028');
tpCmd('magma',      'Magma hot text',                'create-a-magma-hot-text-effect-online-1030');
tpCmd('leaves',     'Natural leaves text',           'natural-leaves-text-effect-931');
tpCmd('discovery',  'Space discovery text',          'create-space-text-effects-online-free-1042');
tpCmd('christmas',  'Christmas tree text',           'christmas-tree-text-effect-online-free-1057');
tpCmd('candy',      'Christmas candy cane text',     'create-christmas-candy-cane-text-effect-1056');
tpCmd('hp',         'Harry Potter text',             'create-harry-potter-text-effect-online-1025');
tpCmd('underwater', 'Underwater 3D text',            '3d-underwater-text-effect-generator-online-1013');

// ── LOGO MAKER — logo1-12/pubg ────────────────────────

async function textpro(url, texts) {
  try {
    return await tp(url, texts);
  } catch { return null; }
}

const logoCmd = (pattern, type, desc, urlPath, dual = false) => {
  cast({ pattern, desc, category: 'textfx', filename: __filename },
  async (conn, mek, m, { from, q, reply }) => {
    try {
      const caption = `_${config.BOT_NAME || 'NEXUS-MD'}_`;
      const prefix = config.PREFIX || '/';
      let text1, text2;
      if (dual) {
        [text1, text2] = (q || '').split(';').map(s => s.trim());
        if (!text1 || !text2) return reply(`*Example:* ${prefix}${pattern} YourText;SubText`);
      } else {
        text1 = q;
        if (!text1) return reply(`*Example:* ${prefix}${pattern} YourName`);
      }
      const baseUrl = type === '1' ? `https://ephoto360.com/${urlPath}.html` :
                      type === '2' ? `https://photooxy.com/${urlPath}.html` :
                      `https://textpro.me/${urlPath}.html`;
      await conn.sendMessage(from, { text: '⏳ *Generating logo...*' }, { quoted: mek });
      const result = await textpro(baseUrl, dual ? [text1, text2] : [text1]);
      if (result?.image) {
        await conn.sendMessage(from, { image: { url: result.image }, caption }, { quoted: mek });
      } else {
        reply('*_Failed to generate logo. Please try again!_*');
      }
    } catch (e) { reply(`❌ Error: ${e.message}`); }
  });
};

logoCmd('logo1', '1', 'Logo: Light glow style', 'hieu-ung-chu/tao-hieu-ung-chu-mam-anh-sang-74');
logoCmd('logo2', '1', 'Logo: Digital glitch style', 'tao-hieu-ung-chu-digital-glitch-truc-tuyen-941');
logoCmd('logo3', '1', 'Logo: Pixel glitch style', 'tao-hieu-ung-chu-pixel-glitch-truc-tuyen-940');
logoCmd('logo4', '1', 'Logo: Street graffiti style', 'tao-hieu-ung-chu-graffiti-duong-pho-an-tuong-online-795');
logoCmd('logo5', '1', 'Logo: Graffiti style 2', 'hieu-ung-chu/chu-graffiti-online-mau-8-182');
logoCmd('logo6', '',  'Logo: Super graffiti (dual text)', 'tao-hieu-ung-chu-graffiti-sieu-ngau-online-794', true);
logoCmd('logo7', '1', 'Logo: Cover graffiti (dual text)', 'hieu-ung-chu/tao-cover-graffiti-online-181', true);
logoCmd('logo8', '1', 'Logo: 3D Gradient (dual text)', 'tao-logo-gradient-3d-truc-tuyen-501', true);
logoCmd('logo9', '1', 'Logo: 3D Text (dual text)', 'tao-logo-chu-truc-tuyen-499', true);
logoCmd('logo10','1', 'Logo: Phub style (dual text)', 'tao-logo-phong-cach-pornhub-612', true);
logoCmd('logo11','1', 'Logo: Avengers style (dual text)', 'tao-logo-3d-phong-cach-avengers-445', true);
logoCmd('logo12','1', 'Logo: Marvel style (dual text)', 'tao-logo-phong-cach-marvel-419', true);

// PUBG logos
logoCmd('pubg1', '1', 'PUBG Logo 1', 'tao-cover-game-pubg-anh-bia-game-playerunknown-s-battlegrounds-401');
logoCmd('pubg2', '1', 'PUBG Logo 2', 'tao-anh-bia-cover-facebook-game-pubg-407');
logoCmd('pubg3', '1', 'PUBG Logo 3', 'tao-logo-pubg-truc-tuyen-mien-phi-714');
logoCmd('pubg4', '1', 'PUBG Logo 4', 'tao-logo-mascot-pubg-online-sieu-ngau-716');
logoCmd('pubg5', '1', 'PUBG Logo 5', 'tao-logo-pubg-truc-tuyen-nhieu-mau-sac-717');
logoCmd('pubg6', '1', 'PUBG Logo 6', 'tao-logo-pubg-phong-cach-chibi-online-721');
logoCmd('pubg7', '1', 'PUBG Logo 7 (dual text)', 'tao-logo-pubg-truc-tuyen-phong-cach-den-trang-715', true);
